version: '3.2'

services:
  app:
    container_name: app
    build: .
    command: yarn start:dev
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=prova_nest
